### ISSUE TITLE
Exception while saving entity with new Alpha 1.4.1.0

### ISSUE THREAD

**Issue by CovertJaguar** [CenturionFox/wolfarmor#10]
```
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:2903) ~[rw.class:?]
	at mcjty.theoneprobe.apiimpl.elements.ElementEntity.<init>(ElementEntity.java:35) ~[ElementEntity.class:?]
	at mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.entity(AbstractElementPanel.java:111) ~[AbstractElementPanel.class:?]
	at mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.entity(AbstractElementPanel.java:117) ~[AbstractElementPanel.class:?]
	at mcjty.theoneprobe.apiimpl.providers.DefaultProbeInfoEntityProvider.showStandardInfo(DefaultProbeInfoEntityProvider.java:155) ~[DefaultProbeInfoEntityProvider.class:?]
	at mcjty.theoneprobe.rendering.OverlayRenderer.getWaitingEntityInfo(OverlayRenderer.java:291) [OverlayRenderer.class:?]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:180) [OverlayRenderer.class:?]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:91) [OverlayRenderer.class:?]
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:104) [ClientProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_647_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:694) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171) [GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at com.attributestudios.wolfarmor.common.capabilities.CapabilityWolfArmor.getHasChest(CapabilityWolfArmor.java:161) ~[CapabilityWolfArmor.class:?]
	at com.attributestudios.wolfarmor.common.capabilities.CapabilityWolfArmor.serializeNBT(CapabilityWolfArmor.java:90) ~[CapabilityWolfArmor.class:?]
	at com.attributestudios.wolfarmor.common.capabilities.CapabilityWolfArmor.serializeNBT(CapabilityWolfArmor.java:36) ~[CapabilityWolfArmor.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1580) ~[rw.class:?]
	... 32 more
```

**Comment by CenturionFox** [comment]
Ah, this looks fun.

Probably just need to store some tracked data as a different data type.

**Comment by CenturionFox** [comment]
I can't reproduce this unfortunately.
